# Generated by Django 6.0.2 on 2026-05-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_and_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskListMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Name')),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('normal', 'Normal')], default='normal', max_length=15)),
                ('status', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
                ('estimated_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Estimated Hrs')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks_and_subtasks.tasklistmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_status', models.CharField(choices=[('inprogress', 'InProgress'), ('billed', 'Billed'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='authentication_and_users.usermaster')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='tasks_and_subtasks.taskmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_task_name', models.CharField(max_length=200, verbose_name='Sub Task Name')),
                ('status', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
                ('estimated_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Estimated Hrs')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks_and_subtasks.taskmaster')),
            ],
        ),
    ]
