# Generated by Django 6.0.2 on 2026-05-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('activity_type', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='Log Date')),
                ('total_spent_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Total Spent Hrs')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_logs', to='customer_and_projects.projectmaster')),
            ],
        ),
    ]
