# Generated by Django 6.0.2 on 2026-05-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_and_users', '0001_initial'),
        ('logging_and_activities', '0001_initial'),
        ('tasks_and_subtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmaster',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tasks_and_subtasks.taskmaster'),
        ),
        migrations.AddField(
            model_name='logmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to='authentication_and_users.usermaster'),
        ),
    ]
