# Generated by Django 6.0.2 on 2026-05-18 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('project_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
                ('progress_percent', models.IntegerField(default=0, verbose_name='Progress Percent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customer_and_projects.customermaster')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=300, verbose_name='Phase Name')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('inprogress', 'InProgress'), ('completed', 'Completed'), ('drop', 'Drop')], default='inprogress', max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='customer_and_projects.projectmaster')),
            ],
        ),
    ]
